// export const stones = [
//     //we are adding a constant for the properties, each is unique and has different values
//     {
//       image: "assets/logo.svg",
//       name: "stefan pants",
//       country: "Kapelstraat 68 C",
//       address: 420,
//       id: 0,
//       allImages: ["assets/logo.svg", "assets/logo.svg", "assets/logo.svg"],
//     },
//     {
//         image: "assets/logo.svg",
//         name: "stefan pants",
//         country: "Kapelstraat 68 C",
//         address: 420,
//         id: 0,
//         allImages: ["assets/logo.svg", "assets/logo.svg", "assets/logo.svg"],
//       },
//       {
//         image: "assets/logo.svg",
//         name: "stefan pants",
//         country: "Kapelstraat 68 C",
//         address: 420,
//         id: 0,
//         allImages: ["assets/logo.svg", "assets/logo.svg", "assets/logo.svg"],
//       },
//       {
//         image: "assets/logo.svg",
//         name: "stefan pants",
//         country: "Kapelstraat 68 C",
//         address: 420,
//         id: 0,
//         allImages: ["assets/logo.svg", "assets/logo.svg", "assets/logo.svg"],
//       },
//       {
//         image: "assets/logo.svg",
//         name: "stefan pants",
//         country: "Kapelstraat 68 C",
//         address: 420,
//         id: 0,
//         allImages: ["assets/logo.svg", "assets/logo.svg", "assets/logo.svg"],
//       },
//       {
//         image: "assets/logo.svg",
//         name: "stefan pants",
//         country: "Kapelstraat 68 C",
//         address: 420,
//         id: 0,
//         allImages: ["assets/logo.svg", "assets/logo.svg", "assets/logo.svg"],
//       },
//       {
//         image: "assets/logo.svg",
//         name: "stefan pants",
//         country: "Kapelstraat 68 C",
//         address: 420,
//         id: 0,
//         allImages: ["assets/logo.svg", "assets/logo.svg", "assets/logo.svg"],
//       },
//       {
//         image: "assets/logo.svg",
//         name: "stefan pants",
//         country: "Kapelstraat 68 C",
//         address: 420,
//         id: 0,
//         allImages: ["assets/logo.svg", "assets/logo.svg", "assets/logo.svg"],
//       },
//       {
//         image: "assets/logo.svg",
//         name: "stefan pants",
//         country: "Kapelstraat 68 C",
//         address: 420,
//         id: 0,
//         allImages: ["assets/logo.svg", "assets/logo.svg", "assets/logo.svg"],
//       },
//       {
//         image: "assets/logo.svg",
//         name: "stefan pants",
//         country: "Kapelstraat 68 C",
//         address: 420,
//         id: 0,
//         allImages: ["assets/logo.svg", "assets/logo.svg", "assets/logo.svg"],
//       }, {
//         image: "assets/logo.svg",
//         name: "stefan pants",
//         country: "Kapelstraat 68 C",
//         address: 420,
//         id: 0,
//         allImages: ["assets/logo.svg", "assets/logo.svg", "assets/logo.svg"],
//       }, 
//       {
//         image: "assets/logo.svg",
//         name: "stefan pants",
//         country: "Kapelstraat 68 C",
//         address: 420,
//         id: 0,
//         allImages: ["assets/logo.svg", "assets/logo.svg", "assets/logo.svg"],
//       },
//        {
//         image: "assets/logo.svg",
//         name: "stefan pants",
//         country: "Kapelstraat 68 C",
//         address: 420,
//         id: 0,
//         allImages: ["assets/logo.svg", "assets/logo.svg", "assets/logo.svg"],
//       },
//   ];
  